### PR TITLE
Added offline functionality

### LINKED ISSUE #23: Offline availability
Have the website be functional when offline.

Ex. using the service workers we did in lab.

### PR DESCRIPTION
**Pull request by mohakvni**

### CODE REVIEW

**Review by kjchou324 — APPROVED** [review]
looks good

**Comment by kjchou324** [comment]
one note, when clicking the mute button the mute icon doesn't seem to work.

**Review by kjchou324 — CHANGES_REQUESTED** [review]
one note, when clicking the mute button the mute icon doesn't seem to work.

**Review by austin-li — APPROVED** [review]
lgtm

**Pull request closed without merging**
